### ISSUE TITLE
buckets, 404 Not Found

### ISSUE THREAD

**Issue by C1ph3R-s** [spreadshirt/backstage-plugin-s3#62]
Hi,

Should I do any further changes after the install based on your doc?
Becase I got this message: 

log:
`"/api/s3/buckets/grouped? HTTP/1.1" 404 "`

GUI:
`Request failed for buckets/grouped, 404 Not Found`

And I do not really understand the cause, the config is working fine and the permission have already been added, I am currently use openshift.

Do you have any suggestions?

**Comment by heyLu** [comment]
Please check if you have all the required config for the backend: https://github.com/spreadshirt/backstage-plugin-s3/tree/main/plugins/s3-viewer-backend, the 404 looks a bit like the routes could be missing from the backend.

Apart from that, are there any other error logs that could be related?  Do any requests to `/api/s3` work?
