### ISSUE TITLE
Add yourself to Community Plugin Directory

### ISSUE THREAD

**Issue by tudi2d** [spreadshirt/backstage-plugin-s3#73]
Hej Spreadshirt-Team,

awesome to see this continous plugin development & maintainance by your team. I wasn't really aware this plugin exists & stumbled over it by luck. Would you be interested in adding yourself to the [community plugin directory](https://backstage.io/plugins/) ([Guide](https://backstage.io/docs/plugins)). This could make it easier for others to discover this plugin & hopefully contributing back to improve it further! :)

Special shout-out to @ivangonzalezacuna for contributing a lot to the community by being active in the Backstage Discord as well as directly contributing to the upstream improving Backstage overall! 🎉

**Comment by ivangonzalezacuna** [comment]
Hi @tudi2d . thanks for the message! :smile: 

We are already in the list of available plugins. You can find it by the name `S3 Viewer`, and owned by `SpreadGroup`.

**Comment by tudi2d** [comment]
ah awesome - totally missed it!
